import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const dmSerifDisplay = localFont({
  src: [
    {
      path: "../public/fonts/dm-serif-display/DMSerifDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/dm-serif-display/DMSerifDisplay-Italic.ttf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-dmSerifDisplay",
  display: "swap",
});

export const futura = localFont({
  src: [
    {
      path: "../public/fonts/futura/Futura-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/futura/Futura-ThinItalic.ttf",
      weight: "100",
      style: "italic",
    },
    {
      path: "../public/fonts/futura/Futura-ThinRegular.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/futura/futura-BookBT.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/futura/Futura-L.ttf",
      weight: "300", // Light
      style: "normal",
    },
    {
      path: "../public/fonts/futura/Futura-M.ttf",
      weight: "500", // Medium
      style: "normal",
    },
    {
      path: "../public/fonts/futura/Futura-B.ttf",
      weight: "700", // Bold
      style: "normal",
    },
  ],
  variable: "--font-futura",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSerifDisplay.variable} ${futura.variable} antialiased min-w-xs`}>
        {children}
      </body>
    </html>
  );
}
